use ProjektBD
Go
CREATE TABLE USERS (
	USERID INT PRIMARY KEY IDENTITY,
	LOGIN VARCHAR(64) NOT NULL,
	FIRSTNAME VARCHAR(255) NOT NULL,
	LASTNAME VARCHAR(255) NOT NULL,
	PASSWORD BINARY NOT NULL,
	DEPARTAMENTID SMALLINT NOT NULL,
	FOREIGN KEY(DEPARTAMENTID) REFERENCES DEPARTAMENT(DEPARTAMENTID),
	CONSTRAINT DEPARTAMENTID CHECK (DEPARTAMENTID > 0 AND DEPARTAMENTID < 32768)
	);