use ProjektBD
Go
CREATE TABLE PRODUCTS (
	PRODUCTID INT PRIMARY KEY IDENTITY (100000, 1),
	PLU BIGINT NULL,
	NAME VARCHAR(255) NOT NULL,
	VATRATEID TINYINT NOT NULL,
	NETPRICE MONEY NOT NULL,
	STOCK INT NOT NULL,
);