Use ProjektBD
Go
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TRIGGER dbo.TRG_VATRATE_UP
   ON dbo.VATRATE
   AFTER UPDATE, DELETE
AS 
BEGIN
	SET NOCOUNT ON;
	RAISERROR(1,-1,-1,'Can not modify or delete VAT rates');
END
GO
