use ProjektBD
Go
CREATE TABLE USERS (
	USERID INT IDENTITY(1,1),
	LOGIN VARCHAR(64) NOT NULL,
	FIRSTNAME VARCHAR(255) NOT NULL,
	LASTNAME VARCHAR(255) NOT NULL,
	PASSWORD BINARY NOT NULL,
	DEPARTAMENTID SMALLINT NOT NULL,
	FOREIGN KEY(DEPARTAMENTID) REFERENCES DEPARTAMENT(DEPARTAMENTID),
	CONSTRAINT USER_DEPARTAMENTID CHECK (DEPARTAMENTID > 0 AND DEPARTAMENTID < 32768),
	CONSTRAINT [PK_USERS] PRIMARY KEY CLUSTERED 
	(
		[USERID] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO