use ProjektBD
Go
CREATE TABLE PRODUCTS (
	PRODUCTID INT PRIMARY KEY IDENTITY (100000, 1),
	PLU BIGINT NULL,
	NAME VARCHAR(255) NOT NULL,
	VATRATEID TINYINT NOT NULL,
	NETPRICE MONEY NOT NULL,
	STOCK INT NOT NULL,
	FOREIGN KEY(VATRATEID) REFERENCES VATRATE(VATRATEID),
	CONSTRAINT PRODUCTS_CHK_PLU CHECK ( PLU > 0 ),
	CONSTRAINT PRODUCTS_CHK_VATRATEID ( VATRATEID > 0 ),
	CONSTRAINT PRODUCTS_CHK_NETSUM ( NETSUM > 0 ),
	CONSTRAINT PRODUCTS_CHK_STOCK( STOCK > 0 ),
);