use ProjektBD
Go
CREATE TABLE PRODUCT (
	PRODUCTID INT IDENTITY (100000, 1),
	PLU BIGINT NULL,
	NAME VARCHAR(255) NOT NULL,
	VATRATEID TINYINT NOT NULL,
	NETPRICE MONEY NOT NULL,
	STOCK INT NOT NULL,
	FOREIGN KEY(VATRATEID) REFERENCES VATRATE(VATRATEID),
	CONSTRAINT PRODUCT_CHK_PLU CHECK ( PLU > 0 ),
	CONSTRAINT PRODUCT_CHK_VATRATEID CHECK ( VATRATEID > 0 ),
	CONSTRAINT PRODUCT_CHK_NETSUM CHECK ( NETPRICE > 0 ),
	CONSTRAINT PRODUCT_CHK_STOCK CHECK ( STOCK > 0 ),
	CONSTRAINT [PK_PRODUCT] PRIMARY KEY CLUSTERED 
	(
		[PRODUCTID] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO