use ProjektBD
Go
CREATE TABLE VATRATE (
	VATRATEID TINYINT IDENTITY(1,1),
	VATRATEAMOUNT REAL NOT NULL
	CONSTRAINT CHK_VATRATEAMOUNT CHECK (VATRATEAMOUNT > 0 AND VATRATEAMOUNT < 1)
	CONSTRAINT UQ_VATRATEAMOUNT UNIQUE (VATRATEAMOUNT)
	CONSTRAINT [PK_VATRATE] PRIMARY KEY CLUSTERED 
	(
		[VATRATEID] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO