use ProjektBD
Go
CREATE TABLE DEPARTAMENT (
	DEPARTAMENTID SMALLINT IDENTITY(1,1),
	NAME VARCHAR(255) NOT NULL,
	SHORT VARCHAR(20) NOT NULL,
	CONSTRAINT [PK_DEPARTAMENT] PRIMARY KEY CLUSTERED 
	(
		[DEPARTAMENTID] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO